on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.9
        
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: |
        scrapy crawl daraz_products -O products.json
        
    - name: Publish product catalog
      uses: actions/upload-artifact@v3.1.2
      with:
        name: product-catalog
        path: products.json
        
