on:
  schedule:
    - cron: "21 */12 * * *"
    
jobs:
  scrape-products:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.9
        
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup Playwright Browsers
      run: |
        playwright install chromium
        
    - name: Run scraper
      run: |
        scrapy crawl daraz_products
        
    - name: Push Updated Catalog
      run: |
        git add products.csv
        git config --global user.name "Scraper Bot"
        git config --global user.email "scraperbot@aars.me"
        git commit -a -m "Product history update"
        git push
